name: Build Workspace Images
on:
  push:
    branches:
      - main
jobs:
  fsd-ubuntu-focal:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ghcr.io/STEAM-Center-NYC/kasm-fsd-ubuntu-focal
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=0
            type=ref,event=branch,priority=100
            type=sha,priority=300
      
      - name: Authenticate with registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push migrator image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: 'Dockerfile'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}